[package]
name = "wordzip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
args = "2.2.0"
getopts = "0.2.21"
itertools = "0.12.0"
sha256 = "1.4.0"

[profile.release]
strip = "debuginfo"
lto = true
